### ISSUE TITLE
Variables in SQL Statement do not work

### ISSUE THREAD

**Issue by Frobeniusnorm** [wangzaixiang/scala-sql#3]
Maybe i used it wrong but 
`connect() executeUpdate
        sql"""INSERT INTO veranstaltungen (name, beschreibung, zeit, zeit_until) VALUES ('$name', '$beschreibung', '$date', '$date')"""`
yields the error 
`Exception in thread "main" java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).`
While it works perfectly fine if i insert the values with the String concat operator.

**Comment by wangzaixiang** [comment]
You should using
```scala
connect() executeUpdate sql"""INSERT INTO veranstaltungen (name, beschreibung, zeit, zeit_until) VALUES ($name, $beschreibung, $date, $date)"""

// which same as insert into ...(name, beschreibung, zeit, zeit_until) values (?, ?, ?, ?),  take 4 parameter
//  but yours sql will be insert into ...(name, beschreibung, zeit, zeit_until) values ('?', '?', '?', '?'), take 0 parameter
```
instead. 

replace '${name}' with ${name}
